### ISSUE TITLE
souporcell: subprocess.CalledProcessError

### ISSUE THREAD

**Issue by RayRay-23** [tuonglab/code_questions#4]
Hi Kelvin, after I setting CPU core=1, and Mem=32G (as suggested by author, maximum memory usage is 25G ), I keep having following error message: 

```pytb
INFO:    fuse: warning: library too old, some operations may not work
checking modules
imports done
checking bam for expected tags
checking fasta
restarting pipeline in existing directory demultiplexed2
remapping
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 572, in <module>
    minimap_tmp_files = remap(args, region_fastqs, all_fastqs)
  File "/opt/souporcell/souporcell_pipeline.py", line 262, in remap
    stdout = samfile, stderr = minierr)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['minimap2', '-ax', 'splice', '-t', '8', '-G50k', '-k', '21', '-w', '11', '--sr', '-A2', '-B8', '-O12,32', '-E2,1', '-r200', '-p.5', '-N20', '-f1000,5000', '-n2', '-m20', '-s40', '-g2000', '-2K50m', '--secondary=no', '/scratch/user/uqjgong1/tmp/mm_ref/refdata-gex-mm10-2020-A/fasta/genome.fa', 'demultiplexed2/tmp.fq']' died with <Signals.SIGKILL: 9>.
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=4564250.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
```
Look forward to any suggestions.
Raymond

**Comment by zktuong** [comment]
Hi Raymond, looking at souporcell's github, there seems to be several minimap2 memory issues which seems related 
there seems to be partial fix, which is to do the hard install with the newest minimap2. Can you give that a try?

**Comment by RayRay-23** [comment]
Thank you Kelvin, I will take a try. Just a quick question. So I should hard install the whole Souporcell software other than just minimap2?

**Comment by zktuong** [comment]
you will need to do all - everything after the Hard install header

**Comment by zktuong** [comment]
Solution was found:
  
Turns out that the chromosome names for the vcf files were not matching to the fasta.
 
So I used:
```
bcftools annotate --rename-chrs chr_name_conv.txt /scratch/user/uqztuong/raymond/vcf_files/out.vcf -Oz -o /scratch/user/uqztuong/raymond/vcf_files/corrected.out.vcf
```
 
where chr_name_conv.txt is just
```
1       chr1
2       chr2
3       chr3
4       chr4
5       chr5
6       chr6
7       chr7
8       chr8
9       chr9
10      chr10
11      chr11
12      chr12
13      chr13
14      chr14
15      chr15
16      chr16
17      chr17
18      chr18
19      chr19
20      chr20
21      chr21
22      chr22
X       chrX
Y       chrY
MT      chrMT
```
 
Then I used:

```
python ~/Softwares/souporcell/souporcell_pipeline.py -i /scratch/user/uqztuong/raymond/Merged_C57_Balb/outs/possorted_genome_bam.bam \
    -b /scratch/user/uqztuong/raymond/Merged_C57_Balb/outs/filtered_feature_bc_matrix/barcodes.tsv.gz \
    -f /home/uqztuong/ref/refdata-gex-mm10-2020-A/fasta/genome.fa \
    --skip_remap True \
    -t 24 -o testout -k 2 --common_variants /scratch/user/uqztuong/raymond/vcf_files/corrected.out.vcf
```

And it succeeded.
 
``` 
python ~/Softwares/souporcell/souporcell_pipeline.py -i /scratch/user/uqztuong/raymond/Merged_C57_Balb/outs/possorted_genome_bam.bam \
    -b /scratch/user/uqztuong/raymond/Merged_C57_Balb/outs/filtered_feature_bc_matrix/barcodes.tsv.gz \
    -f /home/uqztuong/ref/refdata-gex-mm10-2020-A/fasta/genome.fa \
    -t 24 \
    -o testout_remap \
    -k 2 \
    --known_genotypes /scratch/user/uqztuong/raymond/vcf_files/corrected.out.vcf \
    --known_genotypes_sample_names C57BL_6NJ BALB_cJ \
    --aligner HISAT2
 ```

also worked

**Comment by RayRay-23** [comment]
Hi kelvin, 

Thank you very much for resolving this issue. 
I also test the new vcf file with the default aligner mimimap2 and also works. The maximum memory usage is around 400G.

That's really fantastic, enabling me to continue my project.

Cheers!
Raymond

**Comment by zktuong** [comment]
Thanks Raymond. Can you tabulate and see if the singlets/doublets make sense?

**Comment by RayRay-23** [comment]
Hi kelvin,

I think the singlets/doublets make sense. 
The assignment accuracy for Balb_C is 92.4%, for C57 is 99.3%, and doublets detection rate is 54.8%. But also have some wrong assignment can be estimated by (1-accuracy)
The python code for calculating is post below:

import pandas as pd
c57=pd.read_csv("write/C57_barcodes.tsv",header=None)
balb=pd.read_csv("write/Balbc_barcodes.csv",header=None)
merge=pd.read_csv("write/Merged_barcodes.csv",header=None)
cluster=pd.read_table("write/clusters.tsv")
cluster.rename(columns={'cluster0':'balbc','cluster1':'c57'})
cluster['assignment']=cluster['assignment'].strreplace('0','balbc')
cluster['assignment']=cluster['assignment'].replace('1','c57')






true_c57=cluster[cluster['barcode'].isin(c57[0])]
true_c57['status'].value_counts()
true_c57['assignment'].value_counts()
accuracy_c57=true_c57['assignment'].value_counts()[0]/true_c57.shape[0]
true_balb=cluster[cluster['barcode'].isin(balb[0])]
true_balb['status'].value_counts()
true_balb['assignment'].value_counts()
accuracy_balb=true_balb['assignment'].value_counts()[0]/true_balb.shape[0]

#detect doublets
double=set(c57[0]).intersection(set(balb[0]))
pd.Series(list(double)).isin(cluster['barcode']).value_counts()
truedouble=cluster[cluster['barcode'].isin(double)]
truedouble['status'].value_counts()
accuracy_doub=1-truedouble['status'].value_counts()[0]/truedouble.shape[0]

What's your opinion?
Raymond

**Comment by zktuong** [comment]
i think that's not the right way to assess accuracy - you should first create 3 reference lists:

```python
c57_only = list(set(c57) - set(balb))
balb_only = list(set(balb) - set(c57))
c57_balb_intersect = list(set(a).intersection(set(b))))
```

and then use these lists for your `.isin()` steps.

Your accuracy should be out of `c57_only`, `balb_only`, `c57_balb_intersect` where c57_balb_intersect is the putative ground truth doublets.

**Comment by zktuong** [comment]
i think the calculation is a bit off.

this is how i do it:

```python
import pandas as pd
c57=pd.read_csv("/scratch/user/uqjgong1/tmp/c57/outs/filtered_feature_bc_matrix/barcodes.tsv",header=None, sep = "\t")
balbc=pd.read_csv("/scratch/user/uqjgong1/tmp/Balbc/outs/filtered_feature_bc_matrix/barcodes.tsv.gz",header=None, sep = "\t")
merge=pd.read_csv("/scratch/user/uqztuong/raymond/Merged_C57_Balb/outs/filtered_feature_bc_matrix/barcodes.tsv.gz",header=None, sep = "\t")
cluster=pd.read_csv("/scratch/user/uqztuong/raymond/testout/clusters.tsv",sep = "\t")
cluster['assignment']=cluster['assignment'].str.replace('0', 'c57')
cluster['assignment']=cluster['assignment'].str.replace('1','balbc')

c57_only = set(c57[0]) - set(balbc[0])
print(len(c57_only)/len(c57[0]))
balbc_only = set(balbc[0]) - set(c57[0])
print(len(balbc_only)/len(balbc[0]))
setdiff = set(c57[0]).intersection(set(balbc[0]))
print(len(setdiff))

true_c57=cluster[cluster['barcode'].isin(c57_only)]
true_c57['status'].value_counts()
true_c57['assignment'].value_counts()
accuracy_c57=true_c57['assignment'].value_counts()["c57"]/true_c57.shape[0]

true_balb=cluster[cluster['barcode'].isin(balbc_only)]
true_balb['status'].value_counts()
true_balb['assignment'].value_counts()
accuracy_balb=true_balb['assignment'].value_counts()["balbc"]/true_balb.shape[0]

#detect doublets
# double=set(c57[0]).intersection(set(balb[0]))
pd.Series(list(double)).isin(cluster['barcode']).value_counts()
truedouble=cluster[cluster['barcode'].isin(setdiff)]
truedouble['status'].value_counts()
accuracy_doub=truedouble['status'].value_counts()["doublet"]/truedouble.shape[0]

print("C57 accuracy:", accuracy_c57)
#C57 accuracy: 0.9989169116509361
print("Balbc accuracy:", accuracy_balb)
#Balbc accuracy: 0.9970588235294118
print("doublet accuracy:", accuracy_doub)
#doublet accuracy: 0.8064516129032258

```

**Comment by zktuong** [comment]
for completeness, when i used the hisat2 results, it gave me similar accuracies:

```python
#C57 accuracy: 0.9982980040228996
#Balbc accuracy: 0.9964705882352941
#doublet accuracy: 0.8064516129032258
```

**Comment by RayRay-23** [comment]
Hi Kelvin,

I think your calculation is more reasonable. Just a kind reminder that: 0 is Balb_C, 1 is c57. 
If so the accuracy should be 0.998 for C57, 0.932 for Balb_C. 

And for doublets detection, should we use status==doublets or assignment="c57/balbc" as criterion? Doublets accuracy would be 0.371 or 0.532, respectively.

Anyway, I believe this accuracy is good enough for experiment.

Cheers,
Raymond

**Comment by zktuong** [comment]
The vcf order is c57 first, so 0 should be c57.

status == doublet should work. The accuracy i’m getting is 80% for doublets, not 37 or 53%. I wonder if that means the minimap2 accuracy isn’t good

**Comment by RayRay-23** [comment]
Don't know why but I just have a look in ture_c57, and most of them are 1

**Comment by RayRay-23** [comment]
Hi Kelvin,

I guess it has something to do with souporcell argument know_genotype_names.  Because I use the order of Balbc c57, which is different from yours. 

By the way, I think hisat2 has better doublets performance than minimap2.

Thank you

**Comment by zktuong** [comment]
yea. your order should respect the VCF file so it should be C57 then BALBC.

if i were to flip by earlier code above to:
```python
cluster['assignment']=cluster['assignment'].str.replace('1', 'c57') # instead of 0
cluster['assignment']=cluster['assignment'].str.replace('0','balbc') # instead of 1
```

Then you can see that the assignment is wrong
```
>>> true_c57['status'].value_counts()
singlet       6454
unassigned       5
doublet          4
Name: status, dtype: int64
>>> true_c57['assignment'].value_counts()
balbc        6456
balbc/c57       7
Name: assignment, dtype: int64
```
